Don’t crash app if no elastic search is available
Becklyn/SearchBundle pull request #11
Opened 2019-03-21 16:29 UTC by tkasper

The app should not crash if there is no connection to the elastic search

2019-03-21 18:47 UTC, apfelbox commented
I don't think that this is the only place where this exception can be thrown? I thought that the issue also occurs when people are trying to search? That isn't this code path.

2019-03-22 09:10 UTC, apfelbox commented
You need both, of course, as the exception can be thrown in multiple places.

2019-03-22 09:55 UTC, apfelbox commented
Ah, I just saw that you added it in the client directly – which is the correct place. 👍 
However, you missed the `bulk` call further below.

2019-03-22 09:57 UTC, apfelbox commented
Can you also apply the attached patch, please?

2019-03-22 10:41 UTC, apfelbox requested changes

2019-03-22 10:41 UTC, apfelbox commented on Search/SearchIndexer.php
> +use Elasticsearch\Common\Exceptions\NoNodesAvailableException;
⚰️ ?

2019-03-22 10:41 UTC, apfelbox commented on Elasticsearch/ElasticsearchClient.php
>              // add header
The `$this->client->bulk()` call in line 147 is still not protected from throwing exceptions.

2019-03-22 10:56 UTC, tkasper commented
Oh, sorry, didn't see the bulk one. Fixed it.

2019-03-22 10:57 UTC, apfelbox approved these changes

2019-03-22 10:57 UTC, merged